server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB

logging:
  level:
    com.gangku.be: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expMin: ${JWT_EXP_MIN:60}

app:
  s3:
    bucket: ${S3_IMAGE_BUCKET}
    region: ${S3_REGION}
    base-prefix: ${S3_IMAGE_BASE_PREFIX}
    ttl-seconds: ${S3_TTL_SECONDS}
  email:
    from: ${MAIL_FROM}
    verification:
      token-ttl-minutes: 10
      session-ttl-minutes: 60

assets:
  categories:
    - type: image
      prefix: image
      allowed-content-types: [ image/jpeg, image/png, image/webp ]
  data:
    redis:
      port: 6379
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 0
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.starttls.enable: true
